# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/digital_system_study/pill_box/pill_box.cache/wt [current_project]
set_property parent.project_path C:/digital_system_study/pill_box/pill_box.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/digital_system_study/pill_box/pill_box.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/new/VGA.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/buzzer.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/clk_div.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/clk_gen.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/cmd_parse.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/debouncer.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/lb_ctl.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/meta_harden.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/reset_bridge.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/resp_gen.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/rst_gen.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/seg7decimal.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/to_bcd.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/new/top_voice.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/uart_baud_gen.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/uart_rx.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/uart_rx_ctl.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/uart_tx.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/uart_tx_ctl.v
  C:/digital_system_study/pill_box/pill_box.srcs/sources_1/imports/new/bt_uart.v
}
read_ip -quiet C:/digital_system_study/pill_box/pill_box.srcs/sources_1/ip/clk_core/clk_core.xci
set_property used_in_implementation false [get_files -all c:/digital_system_study/pill_box/pill_box.srcs/sources_1/ip/clk_core/clk_core_board.xdc]
set_property used_in_implementation false [get_files -all c:/digital_system_study/pill_box/pill_box.srcs/sources_1/ip/clk_core/clk_core.xdc]
set_property used_in_implementation false [get_files -all c:/digital_system_study/pill_box/pill_box.srcs/sources_1/ip/clk_core/clk_core_ooc.xdc]

read_ip -quiet C:/digital_system_study/pill_box/pill_box.srcs/sources_1/ip/char_fifo/char_fifo.xci
set_property used_in_implementation false [get_files -all c:/digital_system_study/pill_box/pill_box.srcs/sources_1/ip/char_fifo/char_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/digital_system_study/pill_box/pill_box.srcs/sources_1/ip/char_fifo/char_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/digital_system_study/pill_box/pill_box.srcs/sources_1/ip/char_fifo/char_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/digital_system_study/pill_box/pill_box.srcs/constrs_1/imports/new/bt_uart_EGo.xdc
set_property used_in_implementation false [get_files C:/digital_system_study/pill_box/pill_box.srcs/constrs_1/imports/new/bt_uart_EGo.xdc]


synth_design -top bt_uart -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bt_uart.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bt_uart_utilization_synth.rpt -pb bt_uart_utilization_synth.pb"
